### ISSUE TITLE
Why is this asynchronous?

### ISSUE THREAD

**Issue by stephenmathieson** [mafintosh/fs-extended-attributes#1]
Neat module! I've got a quick question tho -

Since the binding works synchronously, I'm curious why the exposed API is async. Is this just future-proofing, or style preference, or...?

**Comment by mafintosh** [comment]
future proofing, far from done, need to make it xplatform and run in a worker

**Comment by stephenmathieson** [comment]
Gotcha, ok. Thanks 👍
